### ISSUE TITLE
Gera um erro caso o usuário insira apenas um número ou dois números sem espaços

### ISSUE THREAD

**Issue by brunoapimentel** [Brenno10/Start-Tech-#1]
https://github.com/Brenno10/Start-Tech-/blob/5925fd425650aee7fba2a796aec6b76c2ab0e303/Final_Project/src/TicTocToe.java#L60

Esse linha gera um erro caso o usuário insira apenas um número de entrada, ou então dois números sem espaços entre eles.

Exemplos:
```
Próximo jogador: o
Escolha a posição (horizontal e vertical)
1
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at Main.gameStart(Main.java:60)
	at Main.main(Main.java:19)
```

**Comment by Brenno10** [comment]
while ( !isNaN(splitNum) || splitNum.length != 2 ) {
Resolvi esse erro

**Comment by Brenno10** [comment]
https://github.com/Brenno10/Start-Tech-/blob/6fabc129465b89dcc01aeb432f3b6c9e74017633/Final_Project/src/TicTocToe.java#L52

Resolvi esse problema

**Comment by brunoapimentel** [comment]
:tada:
